apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
      - name: from-build-pack
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            name: ""
            resources: {}
            workingDir: /workspace/source
            resources:
              requests: {}
            env:
              - name: DOMAIN
                valueFrom:
                  configMapKeyRef:
                    name: ingress-config
                    key: domain
          steps:
            - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
              name: ""
              resources: {}
            - image: klakegg/hugo:0.101.0-ext-alpine
              name: git-submodules
              command:
                - git
              args:
                - submodule
                - update
                - --init
                - --recursive
            - image: gcr.io/cloud-builders/npm
              name: install-dependencies
              command:
                - npm
              args:
                - install
            - image: klakegg/hugo:0.101.0-ext-alpine
              name: build-website
              env:
              - name: HUGO_GH_ACCESS_TOKEN
                valueFrom:
                  secretKeyRef:
                    key: password
                    name: tekton-git
              resources:
                requests:
                  cpu: 400m
                  memory: 512Mi
              script: |
                #!/bin/sh
                hugo -d tmp-website --enableGitInfo --baseURL https://${REPO_NAME}-jx-${REPO_OWNER}-${REPO_NAME}-pr-${PULL_NUMBER}.${DOMAIN}/
            - image: 18fgsa/html-proofer:latest
              name: htmlproofer
              script: |
                #!/bin/sh
                # disabling HTML checks as we have some bad IDs in some pages...
                # --check-html
                htmlproofer ./tmp-website --allow-hash-href --disable-external --checks-to-ignore ScriptCheck --empty-alt-ignore --url-ignore "/#.*/" --file-ignore "/.*apidocs.*/,/.*\/zh.*/,/.*\/es.*/,/.*\/docs\/reference\/api.*/,/.*\/docs\/reference\/config.*/,/.*\/community\/events.*/"
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 30m0s
status: {}
